spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost/taskmanagement?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Jeevitha@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

jwt.secret=3f8a2b1c9d4e7f6a0b5c8d2e1f4a7b3c9d6e2f5a8b1c4d7e0f3a6b9c2d5e8f1
jwt.expiration=86400000
